version: '3'
services:
  bot:
    image: node:12-alpine
    working_dir: /code
    depends_on:
      - mongodb
    volumes:
      - ./:/code
    ports:
      - "9229:9229"
    command: "npm run start:dev"
    user: root
    networks:
      - public
  mongodb:
    image: library/mongo:latest
    networks:
      - public
    ports:
      - "27017:27017"`
networks:
  public:
    driver: bridge
